"""v0.4.2 baseline

Revision ID: 20260819_01
Revises: 
Create Date: 2026-08-19 17:22:11.186526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20260819_01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled_capabilities', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled_formats', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_config', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_providers_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_providers_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_providers_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_providers_name'), ['name'], unique=False)

    op.create_table('asr_scene_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_transcription_use_local', sa.Boolean(), nullable=False),
    sa.Column('recording_evaluation_use_local', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('sync_score', sa.Integer(), nullable=False),
    sa.Column('pronunciation_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_recording_id'), ['recording_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_worker_id'), ['worker_id'], unique=False)

    op.create_table('learning_language_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ui_locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processing_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processing_progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_practice_id', sa.Integer(), nullable=True),
    sa.Column('content_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_content_language'), ['content_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_text_practice_id'), ['text_practice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_translation_language'), ['translation_language'], unique=False)

    op.create_table('material_sentence_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('main_db_recording_id', sa.Integer(), nullable=True),
    sa.Column('main_db_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('fluency_score', sa.Integer(), nullable=False),
    sa.Column('sync_score', sa.Integer(), nullable=False),
    sa.Column('pronunciation_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_sentence_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_sentence_score_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_sentence_score_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_sentence_score_sentence_id'), ['sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_sentence_score_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_mss_main_db_evaluation_id', ['main_db_evaluation_id'], unique=False)
        batch_op.create_index('ix_mss_main_db_recording_id', ['main_db_recording_id'], unique=False)
        batch_op.create_index('ix_mss_user_material_created', ['user_id', 'material_id', 'created_at'], unique=False)
        batch_op.create_index('ix_mss_user_material_sentence_created', ['user_id', 'material_id', 'sentence_id', 'created_at'], unique=False)

    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('asr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recording_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recording_sentence_id'), ['sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recording_status'), ['status'], unique=False)

    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('original_start_time', sa.Float(), nullable=True),
    sa.Column('original_end_time', sa.Float(), nullable=True),
    sa.Column('clip_audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clip_duration', sa.Float(), nullable=True),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentence_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentence_material_id'), ['material_id'], unique=False)

    op.create_table('text_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desired_length', sa.Integer(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_words_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used_words_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unused_words_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_provider_id', sa.Integer(), nullable=True),
    sa.Column('tts_provider_id', sa.Integer(), nullable=True),
    sa.Column('tts_options_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tts_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tts_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tts_audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_practices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_practices_llm_provider_id'), ['llm_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_practices_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_practices_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_practices_tts_job_id'), ['tts_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_practices_tts_provider_id'), ['tts_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_practices_tts_status'), ['tts_status'], unique=False)

    op.create_table('word_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('word_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_word', 'language', name='uq_word_collections_normalized_language')
    )
    with op.batch_alter_table('word_collections', schema=None) as batch_op:
        batch_op.create_index('ix_word_collections_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_collections_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_collections_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_collections_normalized_word'), ['normalized_word'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_collections_sentence_id'), ['sentence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_collections_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_word_collections_normalized_word'))
        batch_op.drop_index(batch_op.f('ix_word_collections_material_id'))
        batch_op.drop_index(batch_op.f('ix_word_collections_language'))
        batch_op.drop_index('ix_word_collections_created_at')

    op.drop_table('word_collections')
    with op.batch_alter_table('text_practices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_practices_tts_status'))
        batch_op.drop_index(batch_op.f('ix_text_practices_tts_provider_id'))
        batch_op.drop_index(batch_op.f('ix_text_practices_tts_job_id'))
        batch_op.drop_index(batch_op.f('ix_text_practices_source_type'))
        batch_op.drop_index(batch_op.f('ix_text_practices_material_id'))
        batch_op.drop_index(batch_op.f('ix_text_practices_llm_provider_id'))

    op.drop_table('text_practices')
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentence_material_id'))
        batch_op.drop_index(batch_op.f('ix_sentence_display_order'))

    op.drop_table('sentence')
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recording_status'))
        batch_op.drop_index(batch_op.f('ix_recording_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_recording_job_id'))

    op.drop_table('recording')
    with op.batch_alter_table('material_sentence_score', schema=None) as batch_op:
        batch_op.drop_index('ix_mss_user_material_sentence_created')
        batch_op.drop_index('ix_mss_user_material_created')
        batch_op.drop_index('ix_mss_main_db_recording_id')
        batch_op.drop_index('ix_mss_main_db_evaluation_id')
        batch_op.drop_index(batch_op.f('ix_material_sentence_score_user_id'))
        batch_op.drop_index(batch_op.f('ix_material_sentence_score_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_material_sentence_score_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_sentence_score_created_at'))

    op.drop_table('material_sentence_score')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_translation_language'))
        batch_op.drop_index(batch_op.f('ix_material_text_practice_id'))
        batch_op.drop_index(batch_op.f('ix_material_job_id'))
        batch_op.drop_index(batch_op.f('ix_material_content_language'))

    op.drop_table('material')
    op.drop_table('learning_language_preferences')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_kind'))
        batch_op.drop_index(batch_op.f('ix_job_created_at'))

    op.drop_table('job')
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_recording_id'))

    op.drop_table('evaluation')
    op.drop_table('asr_scene_settings')
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_name'))
        batch_op.drop_index(batch_op.f('ix_ai_providers_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_ai_providers_is_default'))
        batch_op.drop_index(batch_op.f('ix_ai_providers_capability'))

    op.drop_table('ai_providers')
    # ### end Alembic commands ###
