import { useEffect, useState } from "react";
import { createProvider, deleteProvider, getASRSceneSettings, listProviders, testProvider, updateASRSceneSettings, updateProvider } from "../lib/api";
import type { AIProvider, ASRSceneSettings, ProviderCapability } from "../types";

const capabilities: ProviderCapability[] = ["llm", "tts", "asr"];
export default function SettingsPanel() {
  const [providers, setProviders] = useState<AIProvider[]>([]); const [scenes, setScenes] = useState<ASRSceneSettings | null>(null); const [message, setMessage] = useState("");
  const [draft, setDraft] = useState({ name: "", capability: "llm" as ProviderCapability, provider_type: "openai_compatible", base_url: "", api_key: "", model_name: "" });
  const load = async () => { try { const [p, s] = await Promise.all([listProviders(), getASRSceneSettings()]); setProviders(p); setScenes(s); } catch (e) { setMessage(e instanceof Error ? e.message : "Settings failed to load."); } };
  useEffect(() => { void load(); }, []);
  async function add() { try { await createProvider({ ...draft, is_enabled: true, is_default: !providers.some((p) => p.capability === draft.capability && p.is_default) }); setDraft({ name: "", capability: "llm", provider_type: "openai_compatible", base_url: "", api_key: "", model_name: "" }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not add provider."); } }
  async function test(id: number) { const result = await testProvider(id); setMessage(result.message); }
  async function setDefault(provider: AIProvider) { try { await updateProvider(provider.id, { is_default: true, is_enabled: true }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not set default."); } }
  async function edit(provider: AIProvider) { const base_url = window.prompt("Provider base URL", provider.base_url || ""); if (base_url === null) return; const model_name = window.prompt("Model name", provider.model_name || ""); if (model_name === null) return; const api_key = window.prompt("New API key (leave blank to retain saved key)", ""); if (api_key === null) return; try { await updateProvider(provider.id, { base_url, model_name, api_key: api_key || undefined }); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not update provider."); } }
  async function remove(id: number) { if (!window.confirm("Delete this provider configuration?")) return; try { await deleteProvider(id); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not delete provider."); } }
  async function updateScene(key: "material_transcription_use_local" | "recording_evaluation_use_local", value: boolean) { try { const next = await updateASRSceneSettings({ [key]: value }); setScenes(next); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not update ASR setting."); } }
  return <div className="card settings-panel"><h2>Settings</h2><p className="muted">Credentials stay in the backend. A blank API-key edit retains the saved key.</p>
    <div className="form-grid"><label>Name<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label>Capability<select value={draft.capability} onChange={(e) => setDraft({ ...draft, capability: e.target.value as ProviderCapability })}><option value="llm">LLM</option><option value="tts">TTS</option><option value="asr">ASR</option></select></label><label>Adapter<select value={draft.provider_type} onChange={(e) => setDraft({ ...draft, provider_type: e.target.value })}><option value="openai_compatible">OpenAI-compatible</option>{draft.capability !== "llm" && <option value="azure_speech">Azure Speech</option>}</select></label><label>Base URL<input placeholder="https://…/v1" value={draft.base_url} onChange={(e) => setDraft({ ...draft, base_url: e.target.value })} /></label><label>API key<input type="password" value={draft.api_key} onChange={(e) => setDraft({ ...draft, api_key: e.target.value })} /></label><label>Model<input value={draft.model_name} onChange={(e) => setDraft({ ...draft, model_name: e.target.value })} /></label></div><button disabled={!draft.name || !draft.base_url || !draft.model_name} onClick={() => void add()}>Add provider</button>
    {capabilities.map((capability) => <section key={capability} className="provider-section"><h3>{capability.toUpperCase()}</h3>{providers.filter((provider) => provider.capability === capability).map((provider) => <div className="provider-row" key={provider.id}><span><strong>{provider.name}</strong> · {provider.model_name || "no model"} · {provider.base_url || "no URL"} · {provider.is_enabled ? "enabled" : "disabled"} {provider.api_key_masked ? `· key ${provider.api_key_masked}` : ""}</span><div><button onClick={() => void setDefault(provider)} disabled={provider.is_default}> {provider.is_default ? "Default" : "Set default"}</button><button onClick={() => void edit(provider)}>Edit</button><button onClick={() => void updateProvider(provider.id, { is_enabled: !provider.is_enabled }).then(load).catch((e) => setMessage(e instanceof Error ? e.message : "Could not update provider."))}>{provider.is_enabled ? "Disable" : "Enable"}</button><button onClick={() => void test(provider.id)}>Test</button><button onClick={() => void remove(provider.id)}>Delete</button></div></div>) || <p className="muted">No provider configured.</p>}</section>)}
    <section className="provider-section"><h3>ASR scene routing</h3><label><input type="checkbox" checked={scenes?.material_transcription_use_local ?? true} onChange={(e) => void updateScene("material_transcription_use_local", e.target.checked)} /> Use Local Whisper for material transcription</label><label><input type="checkbox" checked={scenes?.recording_evaluation_use_local ?? true} onChange={(e) => void updateScene("recording_evaluation_use_local", e.target.checked)} /> Use Local Whisper for recording evaluation</label></section>{message && <p className="muted">{message}</p>}</div>;
}
