import { useEffect, useMemo, useState } from "react";
import { generateTextPractice, getJob, importTextPractice, synthesizeTextPractice, updateTextPractice } from "../lib/api";
import type { Material, TextPractice, WordCollection } from "../types";

export default function TextGeneratorPanel({ collections, onMaterialReady }: { collections: WordCollection[]; onMaterialReady: (materialId: number) => void }) {
  const [mode, setMode] = useState<"random" | "manual" | "none">("random");
  const [count, setCount] = useState(5); const [selected, setSelected] = useState<number[]>([]);
  const [topic, setTopic] = useState("daily_life"); const [customTopic, setCustomTopic] = useState("");
  const [language, setLanguage] = useState("en"); const [difficulty, setDifficulty] = useState("intermediate"); const [length, setLength] = useState(180);
  const [practice, setPractice] = useState<TextPractice | null>(null); const [title, setTitle] = useState("My practice text"); const [body, setBody] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [speed, setSpeed] = useState<"slow" | "normal" | "fast">("normal"); const [voice, setVoice] = useState("");
  const selectedSet = useMemo(() => new Set(selected), [selected]);

  useEffect(() => { if (practice) { setTitle(practice.title); setBody(practice.body); } }, [practice]);
  async function generate() { setBusy(true); setMessage(""); try { setPractice(await generateTextPractice({ word_selection: mode, random_word_count: count, word_collection_ids: selected, preset_topic: topic || undefined, custom_topic: customTopic || undefined, target_language: language, difficulty, desired_length: length })); } catch (e) { setMessage(e instanceof Error ? e.message : "Generation failed."); } finally { setBusy(false); } }
  async function saveOrImport() { setBusy(true); setMessage(""); try { const next = practice ? await updateTextPractice(practice.id, { title, body }) : await importTextPractice({ title, body, target_language: language, difficulty, topic: customTopic || topic }); setPractice(next); setMessage("Text saved. You can now create speech."); } catch (e) { setMessage(e instanceof Error ? e.message : "Save failed."); } finally { setBusy(false); } }
  async function createSpeech() { if (!practice) return; setBusy(true); setMessage("TTS job queued."); try { const latest = await updateTextPractice(practice.id, { title, body }); setPractice(latest); const job = await synthesizeTextPractice(latest.id, { speed_preset: speed, voice: voice || undefined }); for (let i = 0; i < 180; i += 1) { await new Promise((resolve) => window.setTimeout(resolve, 1000)); const current = await getJob(job.job_id); setMessage(`TTS: ${current.stage} (${current.progress}%)`); if (current.status === "succeeded") { const materialId = current.result?.material_id; if (typeof materialId === "number") onMaterialReady(materialId); return; } if (current.status === "failed") throw new Error(current.error_message || "TTS failed."); } throw new Error("TTS job timed out in the browser; it will continue on the server."); } catch (e) { setMessage(e instanceof Error ? e.message : "TTS failed."); } finally { setBusy(false); } }
  return <div className="card text-generator"><h2>AI Text</h2><p className="muted">Generate a connected practice passage from your collected words, or paste your own text.</p>
    <div className="form-grid"><label>Word selection<select value={mode} onChange={(e) => setMode(e.target.value as typeof mode)}><option value="random">Random collection</option><option value="manual">Choose words</option><option value="none">No collected words</option></select></label>{mode === "random" && <label>Random count<input type="number" min="0" max={collections.length} value={count} onChange={(e) => setCount(Number(e.target.value))} /></label>}<label>Theme<select value={topic} onChange={(e) => setTopic(e.target.value)}><option value="daily_life">Daily life</option><option value="travel">Travel</option><option value="workplace">Workplace</option><option value="campus">Campus</option><option value="news">News</option><option value="story">Story</option></select></label><label>Custom theme<input value={customTopic} onChange={(e) => setCustomTopic(e.target.value)} /></label><label>Language<input value={language} onChange={(e) => setLanguage(e.target.value)} /></label><label>Difficulty<select value={difficulty} onChange={(e) => setDifficulty(e.target.value)}><option>beginner</option><option>intermediate</option><option>advanced</option></select></label><label>Approx. length<input type="number" min="20" value={length} onChange={(e) => setLength(Number(e.target.value))} /></label></div>
    {mode === "manual" && <div className="word-picker">{collections.map((word) => <label key={word.id}><input type="checkbox" checked={selectedSet.has(word.id)} onChange={() => setSelected((prev) => prev.includes(word.id) ? prev.filter((id) => id !== word.id) : [...prev, word.id])} /> {word.word_text}</label>)}</div>}
    <div className="panel-actions"><button disabled={busy} onClick={() => void generate()}>Generate text</button></div>
    <label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Practice text<textarea rows={10} value={body} onChange={(e) => setBody(e.target.value)} placeholder="Paste text here, then save it and create speech." /></label>
    {practice?.used_words.length ? <p className="muted">Used words: {practice.used_words.join(", ")}{practice.unused_words.length ? ` · Not used: ${practice.unused_words.join(", ")}` : ""}</p> : null}
    <div className="form-grid"><label>Speech speed<select value={speed} onChange={(e) => setSpeed(e.target.value as typeof speed)}><option value="slow">Slow</option><option value="normal">Normal</option><option value="fast">Fast</option></select></label><label>Voice ID / name<input value={voice} onChange={(e) => setVoice(e.target.value)} /></label></div><div className="panel-actions"><button disabled={busy || !body.trim()} onClick={() => void saveOrImport()}>{practice ? "Save edits" : "Save imported text"}</button><button disabled={busy || !practice} onClick={() => void createSpeech()}>Create TTS practice</button></div>{message && <p className="muted">{message}</p>}</div>;
}
